const db_bain_marie__rm_gastro = require('./db/db_product/db_heating_equipment/db_heating__rm_gastro/db_bain_marie__rm_gastro.json')
const db_deep_fryer__rm_gastro = require('./db/db_product/db_heating_equipment/db_heating__rm_gastro/db_deep_fryer__rm_gastro.json')
const db_food_boiler__rm_gastro = require('./db/db_product/db_heating_equipment/db_heating__rm_gastro/db_food_boiler__rm_gastro.json')
const db_grill__rm_gastro = require('./db/db_product/db_heating_equipment/db_heating__rm_gastro/db_grill__rm_gastro.json')
const db_pasta_cooker__rm_gastro = require('./db/db_product/db_heating_equipment/db_heating__rm_gastro/db_pasta_cooker__rm_gastro.json')
const db_pen__rm_gastro = require('./db/db_product/db_heating_equipment/db_heating__rm_gastro/db_pen__rm_gastro.json')
const db_plate__rm_gastro = require('./db/db_product/db_heating_equipment/db_heating__rm_gastro/db_plate__rm_gastro.json')

db_bain_marie__rm_gastro.db_bain_maries__rm_gastro.forEach(bmr => new bain_marie__rm_gastro(bmr).save().catch(e => console.log(e)))
db_deep_fryer__rm_gastro.db_deep_fryers__rm_gastro.forEach(dfs => new deep_fryer__rm_gastro(dfs).save().catch(e => console.log(e)))
db_food_boiler__rm_gastro.db_food_boilers__rm_gastro.forEach(fbs => new food_boiler__rm_gastro(fbs).save().catch(e => console.log(e)))
db_grill__rm_gastro.db_grills__rm_gastro.forEach(gr => new grill_rm_gastro(gr).save().catch(e => console.log(e)))
db_pasta_cooker__rm_gastro.db_pasta_cookers__rm_gastro.forEach(pcs => new pasta_cooker__rm_gastro(pcs).save().catch(e => console.log(e)))
db_pen__rm_gastro.db_pens__rm_gastro.forEach(p => new pen__rm_gastro(p).save().catch(e => console.log(e)))
db_plate__rm_gastro.db_plates__rm_gastro.forEach(plt => new plate__rm_gastro(plt).save().catch(e => console.log(e)))
